### ISSUE TITLE
resource, understand, and solve the edit-able local install question

### ISSUE THREAD

**Issue by windoverwater** [TrustTheVote-Project/VoteTrackerPlus#42]
Convert VoteTrackerPlus to use Python local project installs. This resolves subtle path issues with imports and access to scripts by making them behave the same as if the package had been installed using Pip.

Git is still required to use VTP, but editable installs allow Git to track changes to sources while still using standard Python packaging.

Steps:

- [x] Test using _local editable installs_:
  - [x] For Poetry:
    - [x] Set up `pyproject.toml` to use Poetry as the `build-system`.
    - [x] Specify requirements in `pyproject.toml`
    - [x] Lock the dependencies in `poetry.lock`
    - [x] Add scripts to `tools.poetry.scripts` in `pyproject.toml`
    - [x] Create a virtual environment: `poetry shell` or `poetry install`
    - [x] Perform an editable install: `poetry install`
    - [x] Ensure absolute import paths work
          This means: `from vtp.utils import ...` 
    - [x] Ensure editable source installs that are tracked by Git
  - [x] For Pip + Setuptools:
    - [x] Modify `pyproject.toml` to use `setuptools` as the `build-system`
    - [x] Specify the requirements in `setup.cfg`
    - [x] Add scripts to `tools.poetry.scripts` in `pyproject.toml`
    - [x] Create a virtual environment: `python -m virtualenv`
    - [x] Perform an editable install: `pip install -e .`
    - [x] Ensure absolute import paths work
          This means: `from vtp.utils import ...` 
    - [x] Ensure editable source installs that are tracked by Git
  - ~For Conda~: Deferring on this as its not quite the same as the other two and it's harder for me to test.
- [ ] Test using _regular installs_.
      Note that this means imports work and scripts run. But the scripts will fail if there's no Git repository in the install.

Original post:

> We should figure out the right/better way to deal with distributing the VTP scripts and libraries.
> 
> The original way is to just include the code with the election configuration (currently the mock demo repo) and ballot CVR's effectively all in the same Merkle tree by virtue of git submodules.
> 
> The potential better way is to support an edit-able install across at least poetry and conda.
> At some point the requirement/criteria for 'better' should be listed and agreed too.  However, it seems that some research and perhaps a working example may help regarding the criteria for 'better'.

**Comment by ion-oset** [comment]
Just to be clear: including the election configuration in Git is accomplishing two separate things:

1. Validating the election data and source with a Merkle tree
2. Providing a package distribution mechanism

The purpose of this issue as I see it is to solve using more standard Python mechanism _without_ interfering with the validation.

**Comment by windoverwater** [comment]
Well, I think there may be more with varying priorities:

- providing a CI/CD agile type 'development process' for election officials to create blank ballots AND election configuration data that includes mock election tests within the CI/CD
- providing 'a solution distribution mechanism' with the least moving parts, complexity (UX), and attack surfaces.  Note - one potential 'best' solution here (TBD) is just to provide a container with the merkle tree(s) in it as long as the docker/podman whatever file and its supply chain are also open sourced (just an example possibility).

**Comment by ion-oset** [comment]
I definitely agree that those topics are worth discussing. But they are going to cover a lot more than one issue - and design tradeoffs should be discussed elsewhere. What I am going to tackle first with _this_ issue is being able to install VTP in a way that allows creating a Python package that doesn't have import issues, that works with Poetry and, if possible, Conda, but that still has the Git source install as a subrepo of the data. Right now the installation is brittle and is going to hit tarpit of edge cases that Python installs can fall into. Those need fixing regardless of the question of attack surface (and I am hopeful will be not place any limits on how to solve that question.)

**Comment by ion-oset** [comment]
The steps for this are:

- [ ] Basic editable source installs
  - [  ] For Poetry.
  - [  ] For Conda
- [ ] Ensure absolute import paths work
- [ ] Editable source installs that are tracked by Git.

**Comment by windoverwater** [comment]
Does the "from vtp.utils import ..." line above imply that the scripts should move one directory up so to be under src and next to vtp?  Just asking - not implying that moving is good or bad.

**Comment by ion-oset** [comment]
The important things to know:

1. All the source files should be under `src/vtp`, because that's the root package, as defined in `pyproject.toml`, and package building (among other things) will only detect files below that.

    Beyond that where you put scripts is up to you. The convention I've seen most often would have what you the core or models `src/vtp/core` and the scripts or commands in `src/vtp/cli` (or `scripts`). But again, up to you.

2. When the scripts are _installed_ they will end up in the `bin` directory of your virtual environment. This means that as long as you have activated the virtual environment (with Poetry that means either `source .venv/bin/activate`, `poetry shell`, or `poetry run <command>`) the script will be on your PATH and will just run, no matter what directory your shell is in.

    For example if you have scripts set up in `pyproject.toml` (using the structure I just mentioned to show the package nesting) it would look like:

    ```
    [tool.poetry.scripts]
    accept-ballots = "vtp.cli.accept_ballots:main
    cast-ballots = "vtp.cli.cast_ballots:main
    ```

    You could run them like this:

    ```
    $ poetry shell
    $ accept-ballots --help
    ```

    As long as the virtual environment is active, you can run them from any directory:

    ```
    $ poetry shell
    $ cd ~
    $ accept-ballots --help
    ```

**Comment by windoverwater** [comment]
And FWIIW vtp.cli seems right as well as vtp.core (or vtp.lib if that common - whatever is the most common is probably fine)

**Comment by windoverwater** [comment]
Closing issue as this change is effectively the merge:  https://github.com/TrustTheVote-Project/VoteTrackerPlus/commit/c1d149c137f243270ee3c2ca717619098684d323
