### ISSUE TITLE
Verify the python environment given a local install

### ISSUE THREAD

**Issue by windoverwater** [TrustTheVote-Project/VoteTrackerPlus#48]
With the transition to local installs, to run the VTP scripts now rely on a local install.  Where as with a git deployment the 'local install' could be verified with a 'git status', with a real python local install it would be good to confirm that the activated python environment is correct - in that the user is actually and truly running the code in the local (this) git repo.

So the question is, what are the steps that a python script (that is NOT part of the local install and in fact needs to be executed without referencing the PATH EV - in other words, it is only found in the VoteTrackerPlus repo and never installed) would execute to validate the user is actually and truly running the scripts 'in this git repo'?

**Comment by ion-oset** [comment]
The actual test of whether the user is running the tests "in this git repo" is that you can edit the source script and run the _installed_ command and the command will show the difference. That way you can see that the source has changed using Git and see that the changed is immediately reflected in the installed command.

0. In the project root directory, install the project using either `poetry install` or `pip install -e .` (Note the "." in the Pip install).
1. Edit the source for one of the scripts to print something.
2. Run the script. You should see the result print.

    To do this you can either:
     - Enable the virtual environment (with `poetry shell` or `source .venv/bin/activate`) and run the command (the virtual environment will put it on your PATH).
     
       ```cast-ballot```
     
     - Don't enable the virtual environment and run the script from its installation location:
     
       ```.venv/bin/cast-ballot```
     
If you want this to work from an external script you'll have to do the second one.

**Comment by ion-oset** [comment]
If you want to see how this works, take a look inside the project files as they are installed in the virtual environment:

```
,venv/lib/python3.x/site-packages
  votetrackerplus.pth
  votetrackerplus-0.x.y-distinfo/
```

**Comment by windoverwater** [comment]
Marking this resolved in the sense that given a poetry local install, that 'process' controls/verifies itself as is.  Added a short TL;DR note in the _tools/build/README.md pointing people at the local install files in case they don't want to understand the spec and what is going on.
