### ISSUE TITLE
Need to fix how scripts call scripts

### ISSUE THREAD

**Issue by windoverwater** [TrustTheVote-Project/VoteTrackerPlus#52]
Prior to the local install idiom, a python script could call another python script via a known relative path.  Post the local install it needs to call the script via the (poetry) managed PATH and via the installed name, not the python script name.

In other words, the setup-vtp-demo design is busted in that the submodule VoteTrackerPlus repo must exist and the poetry env based scripts call into the submodule.  Which is broken and needs to be fixed.

**Comment by stratofax** [comment]
I think you want to use the import statement, like you're already doing in this example from [cast_ballot.py](https://github.com/TrustTheVote-Project/VoteTrackerPlus/blob/df167fe26fe256fdd76594fbc4516d925fd77f2a/src/vtp/cast_ballot.py)

```
# Local imports
from vtp.utils.address import Address
from vtp.utils.ballot import Ballot, BlankBallot, Contests
from vtp.utils.common import Globals, Shellout
from vtp.utils.election_config import ElectionConfig
```
