### ISSUE TITLE
move the scripts to a cli subdir and rename utils to core

### ISSUE THREAD

**Issue by windoverwater** [TrustTheVote-Project/VoteTrackerPlus#67]

**Comment by stratofax** [comment]
Maybe just set the path as `vtp.core` and drop the `votetrackerplus` part?

**Comment by windoverwater** [comment]
Yes! - that seems right.  Thanks!

**Comment by windoverwater** [comment]
Post yesterday's zoom mtg, switching this to be move the scripts to a cli subdir and switch utils to core
